[project]
name = "dynamodx"
version = "0.1.2"
description = "Developer-friendly library for DynamoDB with single-table design, without ORM lock-in."
readme = "README.md"
authors = [
    { name = "Sérgio Rafael Siqueira", email = "osergiosiqueira@gmail.com" },
]
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",

    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",

    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Typing :: Typed",

    "Topic :: Database",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "aws",
    "dynamodb",
    "database",
]
dependencies = [
    "boto3>=1.42.39",
    "jmespath>=1.1.0",
]

[project.urls]
Homepage = "https://github.com/sergiors/dynamodx"
Repository = "https://github.com/sergiors/dynamodx"
Issues = "https://github.com/sergiors/dynamodx/issues"

[dependency-groups]
dev = [
    "boto3-stubs[essential]>=1.42.39",
    "jsonlines>=4.0.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.14",
]

[tool.pytest.ini_options]
addopts = "--cov=dynamodx --cov-report html"

[tool.ruff]
target-version = "py311"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"